{{- if .Values.secret.enabled -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Chart.Name }}
  namespace: {{ required "namespace is missing" .Values.namespace }}
type: Opaque
data:
  token: {{ required "spotinst.token is missing" .Values.spotinst.token | b64enc }}
  account: {{ required "spotinst.account is missing" .Values.spotinst.account | b64enc }}
{{- end -}}
